name: Java CI

on:
  repository_dispatch:
    types: run-tests
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - addCI
jobs:
  API-Performance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Performance Test
        run: mvn -Dgatling.simulationClass=apitest.verifyUser clean gatling:test
      - uses: actions/upload-artifact@v1
        with:
          name: report
          path: target
      - name: Print Run id
        run: echo $GITHUB_RUN_ID

#curl -H "Accept: application/vnd.github.everest-preview+json" \
#  -H "Authorization: token <TOKEN>" \
#  --request POST \
#  --data '{"event_type": "run-tests"}' \
#  https://api.github.com/repos/ProjectEKA/APIPerformanceTests/dispatches